# Generated by Django 5.0.7 on 2024-08-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Work_type', models.CharField(choices=[('carpenter', 'carpenter'), ('plumber', 'plumber'), ('mechanic', 'mechanic'), ('construction', 'construction'), ('mining', 'mining'), ('cook', 'cook'), ('teacher', 'teacher')], max_length=50)),
                ('user', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('Place', models.CharField(max_length=120)),
                ('Description', models.TextField(blank=True)),
            ],
        ),
    ]
